[package]
name = "quickwit-doc-mapper"
description = "Index schema and document mapping"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
dyn-clone = { workspace = true }
fnv = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
siphasher = { workspace = true }
tantivy = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
typetag = { workspace = true }
utoipa = { workspace = true }

quickwit-common = { workspace = true }
quickwit-datetime = { workspace = true }
quickwit-macros = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-query = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
matches = { workspace = true }
serde_yaml = { workspace = true }
time = { workspace = true }

quickwit-query = { workspace = true, features = ["multilang"] }

[features]
multilang = ["quickwit-query/multilang"]
testsuite = []

[[bench]]
name = "doc_to_json_bench"
harness = false

[[bench]]
name = "routing_expression_bench"
harness = false
